//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.TW;

[assembly: RegisterDocumentType(SiteConfiguration.CLASS_NAME, typeof(SiteConfiguration))]

namespace CMS.DocumentEngine.Types.TW
{
	/// <summary>
	/// Represents a content item of type SiteConfiguration.
	/// </summary>
	public partial class SiteConfiguration : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "TW.SiteConfiguration";


		/// <summary>
		/// The instance of the class that provides extended API for working with SiteConfiguration fields.
		/// </summary>
		private readonly SiteConfigurationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SiteConfigurationID.
		/// </summary>
		[DatabaseIDField]
		public int SiteConfigurationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SiteConfigurationID"), 0);
			}
			set
			{
				SetValue("SiteConfigurationID", value);
			}
		}


		/// <summary>
		/// Site logo.
		/// </summary>
		[DatabaseField]
		public string SiteConfigurationLogo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SiteConfigurationLogo"), @"");
			}
			set
			{
				SetValue("SiteConfigurationLogo", value);
			}
		}


		/// <summary>
		/// Footer text.
		/// </summary>
		[DatabaseField]
		public string SiteConfigurationFooterText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SiteConfigurationFooterText"), @"");
			}
			set
			{
				SetValue("SiteConfigurationFooterText", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SiteConfiguration fields.
		/// </summary>
		[RegisterProperty]
		public SiteConfigurationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SiteConfiguration fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SiteConfigurationFields : AbstractHierarchicalObject<SiteConfigurationFields>
		{
			/// <summary>
			/// The content item of type SiteConfiguration that is a target of the extended API.
			/// </summary>
			private readonly SiteConfiguration mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SiteConfigurationFields" /> class with the specified content item of type SiteConfiguration.
			/// </summary>
			/// <param name="instance">The content item of type SiteConfiguration that is a target of the extended API.</param>
			public SiteConfigurationFields(SiteConfiguration instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SiteConfigurationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SiteConfigurationID;
				}
				set
				{
					mInstance.SiteConfigurationID = value;
				}
			}


			/// <summary>
			/// Site logo.
			/// </summary>
			public string Logo
			{
				get
				{
					return mInstance.SiteConfigurationLogo;
				}
				set
				{
					mInstance.SiteConfigurationLogo = value;
				}
			}


			/// <summary>
			/// Footer text.
			/// </summary>
			public string FooterText
			{
				get
				{
					return mInstance.SiteConfigurationFooterText;
				}
				set
				{
					mInstance.SiteConfigurationFooterText = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SiteConfiguration" /> class.
		/// </summary>
		public SiteConfiguration() : base(CLASS_NAME)
		{
			mFields = new SiteConfigurationFields(this);
		}

		#endregion
	}
}